# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: npm ci
  displayName: 'Install dependencies'

- script: npm install
  workingDirectory: ./myapp
  displayName: 'Install dependencies for Express app'

- script: |
    npm start &
    sleep 5
  workingDirectory: ./myapp
  displayName: 'Start Express server'
  
- script: npx playwright install --with-deps
  displayName: 'Install Playwright Browsers'

- script: npx playwright test
  displayName: 'Run Playwright tests'
  
- task: PublishPipelineArtifact@1
  condition: always()
  inputs:
    targetPath: 'playwright-report/'
    artifact: 'playwright-report'
    publishLocation: 'pipeline'